FORMAT: 1A
HOST: http://knights-manager.herokuapp.com

# Knights-Manager 

Knights-Manager is an API allowing users to register, search, upload and download
student project reports

## Search [/projects/search/{?q}]

### Search a project report [GET]

You can perform a query on our collection for project matches using this action.

+ Parameters
    + q - query

+ Response 200 (application/json)

        [
            {
                "title": "Faulty Intake Manifold",
                "Authors": ["Joe Ibadon",
                            "Frank Good"],
                "filename": "3sjal8734bv49w838pqv08n8v348yibufuwk",
                "size": "254452".
                "submit_date": "2019-06-07"
            },
            {
                "title": "The Conjuring",
                "Authors": ["Joe Wakens",
                            "McWenolds",
                            "Charles Preston"],
                "filename": "9jou4nfhi8w4rona3498yc3wcc74jurj3imbf",
                "size": "254452".
                "submit_date": "2017-03-07"
            }
        ]

## Projects [/projects]

### Get project reports [GET]

Use this end point to get a repository of projects in our collection


+ Response 200 (application/json)

        [
            {
                "title": "Faulty Intake Manifold",
                "Authors": ["Joe Ibadon",
                            "Frank Good"],
                "filename": "3sjal8734bv49w838pqv08n8v348yibufuwk",
                "size": "254452".
                "submit_date": "2019-06-07"
            },
            {
                "title": "The Conjuring",
                "Authors": ["Joe Wakens",
                            "McWenolds",
                            "Charles Preston"],
                "filename": "9jou4nfhi8w4rona3498yc3wcc74jurj3imbf",
                "size": "254452".
                "submit_date": "2017-03-07"
            },
            {
                "title": "Cloaking Methods",
                "Authors": ["John Prey",
                            "Scott Presley",
                            "Evan Mcguire"],
                "filename": "9jou4nfhi8w4rona3498yc3wcc74jurj3imbf",
                "size": "254452".
                "submit_date": "2017-03-07"
            },
            {
                "title": "The Pressure Point Of Mammals",
                "Authors": ["Ella Vert",
                            "James Quitso",
                            "Carl Jenna"],
                "filename": "90jomoc56sc5ecj88rc4s4tzscwfxry5w4zq33",
                "size": "39997".GET
                "submit_date": "2017-03-07"
            }
        ]
        

## Contact us [/]

### Get our remaining endpoints

To get all our API end points, contact our developers at `knights.of.coe3@gmail.com`