FORMAT: 1A
HOST: http://knights-manager.herokuapp.com

# Knights-Manager 

Knights-Manager is an API allowing users to register, search, upload and download
student project reports

## Login [/auth/login]

### Login a user [POST]
You can login a user by sending their email and password. Please take note 
of the auth token for you will need it for all user requests.

+ Request (application/json)

        {
            "email": "example@gmail.com",
            "password": "123456"
        }
        
+ Response 201 (application/json)

        {
            "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MDM0ODQ5OTYsImlhdCI6MTUwMzM5ODU4Niwic3ViIjo1fQ.GC6IEOohdo_xrz9__UeugIlir0qtJdKbEzBtLgqjt5A",
            "message": "Successfully registered",
            "status": "success"
        }

+ Response 202 (application/json)

        {
          "message": "Content-type must be json",
          "status": "failed"
        }

+ Response 401 (application/json)

        {
          "message": "Missing or wrong email format or password is less than four characters",
          "status": "failed"
        }
        
+ Response 401 (application/json)

        {
          "message": "User does not exist or password is incorrect",
          "status": "failed"
        }
        
## Logout [/auth/logout]

### Log out a user [POST]

You can log out a user by sending a request with their email and address. The
auth token will then be invalidated.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer JWT Token

+ Response 200 (application/json)

        {
            "message": "Successfully logged out",
            "status": "success"
        }
        
+ Response 403 (application/json)

        {
          "message": "Provide a valid auth token",
          "status": "failed"
        }

+ Response 403 (application/json)

        {
          "message": "Provide an authorization header",
          "status": "failed"
        }
        
+ Response 401 (application/json)

        {
          "message": "Signature expired, Please sign in again",
          "status": "failed"
        }
        
+ Response 401 (application/json)

        {
          "message": "Invalid token. Please sign in again",
          "status": "failed"
        }


## Search [/projects/search/{?q}]

### Search a project report [GET]

You can perform a query on our collection for project matches using this action.

+ Parameters
    + q - query

+ Response 200 (application/json)

        [
            {
                "title": "Faulty Intake Manifold",
                "Authors": ["Joe Ibadon",
                            "Frank Good"],
                "filename": "3sjal8734bv49w838pqv08n8v348yibufuwk",
                "size": "254452".
                "submit_date": "2019-06-07"
            },
            {
                "title": "The Conjuring",
                "Authors": ["Joe Wakens",
                            "McWenolds",
                            "Charles Preston"],
                "filename": "9jou4nfhi8w4rona3498yc3wcc74jurj3imbf",
                "size": "254452".
                "submit_date": "2017-03-07"
            }
        ]

## Projects [/projects]

### Get project reports [GET]

Use this end point to get a repository of projects in our collection


+ Response 200 (application/json)

        [
            {
                "title": "Faulty Intake Manifold",
                "Authors": ["Joe Ibadon",
                            "Frank Good"],
                "filename": "3sjal8734bv49w838pqv08n8v348yibufuwk",
                "size": "254452".
                "submit_date": "2019-06-07"
            },
            {
                "title": "The Conjuring",
                "Authors": ["Joe Wakens",
                            "McWenolds",
                            "Charles Preston"],
                "filename": "9jou4nfhi8w4rona3498yc3wcc74jurj3imbf",
                "size": "254452".
                "submit_date": "2017-03-07"
            },
            {
                "title": "Cloaking Methods",
                "Authors": ["John Prey",
                            "Scott Presley",
                            "Evan Mcguire"],
                "filename": "9jou4nfhi8w4rona3498yc3wcc74jurj3imbf",
                "size": "254452".
                "submit_date": "2017-03-07"
            },
            {
                "title": "The Pressure Point Of Mammals",
                "Authors": ["Ella Vert",
                            "James Quitso",
                            "Carl Jenna"],
                "filename": "90jomoc56sc5ecj88rc4s4tzscwfxry5w4zq33",
                "size": "39997".GET
                "submit_date": "2017-03-07"
            }
        ]
        

## Contact us [/]

### Get our remaining endpoints [GET]

To get all our API end points, contact our developers at `knights.of.coe3@gmail.com`