"""removed programme column

Revision ID: 226f3f41b93f
Revises: 9f8ec045f42e
Create Date: 2019-06-08 19:20:59.602585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226f3f41b93f'
down_revision = '9f8ec045f42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_programme', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'programme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('programme', sa.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_programme', 'user', ['programme'], unique=False)
    # ### end Alembic commands ###
