"""create indices

Revision ID: 9f8ec045f42e
Revises: a1316b7b88ae
Create Date: 2019-06-06 20:36:57.066199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8ec045f42e'
down_revision = 'a1316b7b88ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_authors'), 'project', ['authors'], unique=False)
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    op.create_index(op.f('ix_user_department'), 'user', ['department'], unique=False)
    op.create_index(op.f('ix_user_institution'), 'user', ['institution'], unique=False)
    op.create_index(op.f('ix_user_programme'), 'user', ['programme'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_programme'), table_name='user')
    op.drop_index(op.f('ix_user_institution'), table_name='user')
    op.drop_index(op.f('ix_user_department'), table_name='user')
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_index(op.f('ix_project_authors'), table_name='project')
    # ### end Alembic commands ###
