"""removed programme column

Revision ID: a9f568dd1436
Revises: 
Create Date: 2019-06-08 19:11:47.478001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f568dd1436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=32), nullable=False),
    sa.Column('lastname', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pwhash', sa.String(length=128), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_department'), 'user', ['department'], unique=False)
    op.create_index(op.f('ix_user_institution'), 'user', ['institution'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('submit_date', sa.DateTime(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_project_authors'), 'project', ['authors'], unique=False)
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_index(op.f('ix_project_authors'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_institution'), table_name='user')
    op.drop_index(op.f('ix_user_department'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
